version: '2'
services:
  e2e-tests:
    image: danielsomerfield/e2e-tests:${VERSION}
    build:
      context: ./howami-e2e
      args:
        version: ${VERSION}
    depends_on:
      - howami-service
      - comms-service
      - kafka
    links:
      - mongo
      - howami-service
      - comms-service
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      - HOWAMI_SERVICE_BASE_URL=http://howami-service
      - COMMS_SERVICE_BASE_URL=http://comms-service
