version: '2'
services:
  mongo:
    image: mongo:3.4
    expose:
      - 27017
    ports:
      - 27017:27017

  zookeeper:
    image: zookeeper:3.4.10
    expose:
      - 2181
    ports:
      - 2181:2181

  kafka:
    image: wurstmeister/kafka:1.0.0
    links:
      - zookeeper
    expose:
      - 9092
    ports:
      - 9092:9092
    environment:
      - KAFKA_ZOOKEEPER_CONNECT=zookeeper:2181
      - KAFKA_ADVERTISED_HOST_NAME=kafka