version: '2'
services:
  mongo:
    image: mongo:3.4
    expose:
      - 27017
    ports:
      - 27017:27017

  zookeeper:
    image: zookeeper:3.4.10

  kafka:
    image: wurstmeister/kafka:1.0.0
    links:
      - zookeeper
    environment:
      - KAFKA_ZOOKEEPER_CONNECT=zookeeper:2181