version: 2
jobs:
  build:
    docker:
      - image: danielsomerfield/howami-docker-primary:latest

    steps:
      - checkout
      - setup_remote_docker
      - run: make build
      - run: make integration

      - store_test_results:
          paths:
            - howami-service/build/test-results
            - test_result