version: 2
jobs:
  build:
    docker:
      - image: danielsomerfield/howami-docker-primary:latest

    steps:
      - checkout
      - setup_remote_docker
      - run: make build
      - run: make integration
      - run: make e2e

      - store_test_results:
          paths:
            - howami-service/build/test-results

      - store_artifacts:
          path: e2e-test.log

      - store_artifacts:
          path: all.log

      - store_artifacts:
          path: howami-service/build/test-results