version: 2
jobs:
  build:
    docker:
      - image: danielsomerfield/howami-docker-primary:latest

    steps:
      - run: minikube start
      - checkout
      - setup_remote_docker
      - run: make build
      - run: make integration
      - run: make run-local
      - run: make smoke
      - run: make push

      - store_test_results:
          paths:
            - howami-service/build/test-results

      - store_artifacts:
          path: smoke-test.log

      - store_artifacts:
          path: all.log

      - store_artifacts:
          path: howami-service/build/test-results