apiVersion: batch/v1
kind: Job
metadata:
  name: smoke
spec:
  template:
    metadata:
      labels:
        app: howami-smoke-test
        group: howami-all
    spec:
      containers:
      - name: e2e
        image: danielsomerfield/e2e-tests:1.0-55
      restartPolicy: Never
  backoffLimit: 4
